paths:
  contracts: "contracts"

environment: .env

networks:
  default: studionet

  localnet: {}
  studionet: {}
  testnet_bradbury:
    url: "https://rpc-bradbury.genlayer.com"
    accounts:
      - "${ACCOUNT_PRIVATE_KEY}"
