export type CampaignStatus = "OPEN" | "PAUSED" | "CLOSED";
export type SubmissionStatus = "PENDING" | "APPROVED" | "REJECTED" | "CLAIMED";

export type Campaign = {
  campaignId: number;
  owner: string;
  title: string;
  productUrl: string;
  taskInstruction: string;
  proofRequirement: string;
  rewardPool: bigint;
  rewardPerApproved: bigint;
  stakeRequired: bigint;
  minimumScore: number;
  status: CampaignStatus;
  submissionCount: number;
  approvedCount: number;
  rejectedCount: number;
  expectedRecipient: string;
  expectedMethod: string;
  expectedTaskIdentifier: string;
  reservedRewardPool: bigint;
  availableRewardSlots: number;
};

export type Submission = {
  submissionId: number;
  campaignId: number;
  campaignTitle: string;
  tester: string;
  transactionUrl: string;
  appResultUrl: string;
  feedbackText: string;
  stakeAmount: bigint;
  status: SubmissionStatus;
  score: number;
  approved: boolean;
  rewardAmount: bigint;
  transactionSuccess: boolean;
  identityMatch: boolean;
  taskCompleted: boolean;
  usageValid: boolean;
  proofScore: number;
  feedbackScore: number;
  insightScore: number;
  originalityScore: number;
  reasonSummary: string;
  evidenceSummary: string;
  improvementRecommendation: string;
  riskFlags: string;
  rubricVersion: string;
  validationMethod: string;
  transactionAnalysis: string;
  identityAnalysis: string;
  taskAnalysis: string;
  proofReason: string;
  feedbackReason: string;
  insightReason: string;
  originalityReason: string;
  consensusChecks: string;
  settlementExplanation: string;
  evidenceTransactionHash: string;
  evidenceOutcomeKey: string;
  reservedRewardAmount: bigint;
  reservationStatus: "RESERVED" | "CONSUMED" | "RELEASED";
  recipientMatch: boolean;
  methodMatch: boolean;
  taskIdentifierMatch: boolean;
  bindingAnalysis: string;
  claimed: boolean;
};

export type CampaignForm = {
  title: string;
  productUrl: string;
  taskInstruction: string;
  proofRequirement: string;
  rewardPool: string;
  rewardPerApproved: string;
  stakeRequired: string;
  minimumScore: string;
  expectedRecipient: string;
  expectedMethod: string;
  expectedTaskIdentifier: string;
};

export type ProofForm = {
  transactionUrl: string;
  appResultUrl: string;
  feedbackText: string;
};
